### ISSUE TITLE
Should they be called "friend requests" in the STS?

### ISSUE THREAD

**Issue by alexskc** [Tox-Archive/Tox-STS#3]
The way I see it, certain people you "friend" might not really be friends. They could be coworkers, or acquaintances, or business partners, or just about anything. Calling them "friends" instead of a generic phrase like "contacts" is more friendly, in a way, but it is limiting.

This becomes even more confusing if a Tox client wants to implement some kind of circles-like feature as a way of organizing contacts.

**Comment by Tirifto** [comment]
Just tuning in to express my support for this change. I don't think calling all contacts 'friends' is a good idea.

**Comment by Tirifto** [comment]
Note: This issue was discussed in [qTox issue 1855](https://github.com/tux3/qTox/issues/1855), while STS was stagnant. Now it's hopefully alive again, so I'm linking to the discussion, which (I assume) should now continue here.

And since I haven't noticed any noteworthy alternative suggestions, I suppose voting and discussion should be led concerning the change of 'friend' to 'contact'.

**Comment by x368** [comment]
Surely a contact list is __not__ the same as a list of your friends. There is a lot of people who you talk to who are _not_ your friends (your boss; the colleagues; a handsome stranger; various shops' employees and so on).

Misleading the users to by default trust their contacts (or to generally blindly trust anything) may be good for centralized services but is damaging to the users, whose interests Tox aims to represent.

Of course the wording _must_ be changed in the STS.

**Comment by aaannndddyyy** [comment]
+1 for renaming "friends" to "contacts". "friends2 is simply inadequate in many contexts.

**Comment by antis81** [comment]
+1 for renaming "friends" to "contacts".
