### ISSUE TITLE
Support for encryption should not be an option, but a requirement.

### ISSUE THREAD

**Issue by zetok** [Tox-Archive/Tox-STS#45]
There may be a common option that encryption is useless if "attacker" has access to system.

Bullshit.

In most of cases, password-protected encryption is the only thing that helps users avoid real problems. If that feature would be missing, Tox would be blamed for all of those problems (you don't want that).

By most of cases I mean that there is no "attacker" that is able to use some sort of sophisticated attack.

I'm talking about the kind of "attack" like:
* "parents went through my chat history and now I'm grounded"
* "over-jealous wife/girlfrend saw my chats with someone named '(…) best grill' and I'm fucked"

For those users password-protected encryption is essential, and as such should be a requirement for Tox client.

Edit: to be precise, I want **support** for encryption to be mandatory, whether someone will actually use this feature is up to them.

**Comment by novist** [comment]
Agreed. Even though i think only very small fraction of users will use it choice is always good.

**Comment by GrayHatter** [comment]
I want to add strong support for encryption being optional requirement. So that all clients should offer it, but none of them should make it mandatory.

Requiring encryption requires a separate key, potentially requiring users to enter another password on boot. Eventually the user will disable Tox start on boot, instead of disabling the password. Hindering adoption in replacement of Skype.

**Comment by stqism** [comment]
@GrayHatter I'd have to agree with the optional mark, if we hinder the UX with this and scare people away we'd have effectively lost.

**Comment by zetok** [comment]
Additional note: encryption should not be limited to Tox profile data and history, but all files, e.g. avatars, settings files, etc.

**Comment by zetok** [comment]
```

[01:36:36] <grayhatter> zetok: does qtox have encrpyted personal data?
[01:36:53] <zetok> profile + history
[01:37:16] <zetok> rest (i.e. avatars, .ini settings, avatar hashes) is not encrypted
[01:37:42] <grayhatter> anyone think that toxcore should offer a way to store data in a single global file that will be cross compatible?
[01:37:50] <zetok> yeah
[01:38:12] <zetok> problems is arbitrary data
[01:38:21] <grayhatter> so that I can dump a file of any type in an enum and get it back?
[01:38:28] <grayhatter> then just encrpyt that file?
[01:38:31] <zetok> hm
[01:38:49] <zetok> wouldn't it be better to standardize the way in which files are being made?
[01:39:05] <zetok> i.e. why not make "savefile" a "tarball", but encrypted?
[01:39:20] <grayhatter> what do you mean?
[01:39:20] <zetok> and the way in which contents of "tarbal" are organized should be standardized
[01:39:32] <grayhatter> oh
[01:39:34] <grayhatter> yeah
[01:39:50] <grayhatter> maybe not
[01:40:13] <grayhatter> does the winapi offer an API for tar'd data?
[01:40:18] <zetok> erm
[01:40:22] <zetok> "tarball"
[01:40:23] <grayhatter> it'd add bloat
[01:40:30] <zetok> tux3 was saying something about using .zip for that
[01:40:42] <grayhatter> still not x-compat
[01:41:19] <grayhatter> and unless I'm mistaken, you can't encrypt filenames on a .zip
[01:41:36] <zetok> well, I don't know
[01:41:54] <zetok> it's better to ask tux3 what his thoughts on that matter are
[01:42:20] <zetok> and then standardize it → i.e. making an issue on STS, where client devs could say what their opinions on the matter are
[01:42:40] <zetok> both dvor and subliun should say what they think about it
````
@dvor, @Impyy, @irungentoo, @tux3, @subliun ↑ you probably want to standardize it `:)`

**Comment by ProMcTagonist** [comment]
+1 for requiring encryption support and +1 for encrypting all user data

**Comment by GrayHatter** [comment]
:-1: for requiring encryption

**Comment by tux3** [comment]
I don't think encryption of the save file should be a requirement. Don't get me wrong, it should be very strongly recommended in the vast majority of cases, and as you said it does avoid real problems. 

But there are use cases where a Tox client does not need or want to password protect the save data.
Look at the various Tox bots, those don't need to be password protected. Look at people using full disk encryption, they don't need an extra layer to use Tox. We also need to account for people using the Tox network in unexpected ways (not just for chatting). 

These scenarios should be permitted by the STS. Under those use cases the Tox clients can properly integrate with the network, they can interoperate with other clients, and so they should be STS standard compliant, without needing save file encryption. We don't want to force those clients to implement save encryption just to follow the standard and then never use it because it doesn't actually match their use case.

What I think should be standardized is that IF a client decides to use encryption then it MUST follow the format described in the STS, so as to stay compatible with other clients. But save-file encryption should not be required, merely strongly recommended.

**Comment by dvor** [comment]
> What I think should be standardized is that IF a client decides to use encryption then it MUST follow the format described in the STS, so as to stay compatible with other clients. But save-file encryption should not be required, merely strongly recommended.

I agree with that point.

**Comment by zetok** [comment]
>I don't think encryption of the save file should be a requirement.

When it was said that encrypting it should be a requirement? This is **not** what this is about.

>Look at the various Tox bots, those don't need to be password protected. 

Bots aren't Tox clients.

>Look at people using full disk encryption, they don't need an extra layer to use Tox. 

Almost no one uses that.

>We also need to account for people using the Tox network in unexpected ways (not just for chatting). 

Again, not Tox clients. "Using Tox network" ≠ "Tox client"

>These scenarios should be permitted by the STS. Under those use cases the Tox clients can properly integrate with the network, they can interoperate with other clients, and so they should be STS standard compliant, without needing save file encryption. 

STS is a standard for The Tox Client. Anything that doesn't aspire to be it has no obligation whatsoever to follow it.

>What I think should be standardized is that IF a client decides to use encryption then it MUST follow the format described in the STS, so as to stay compatible with other clients. But save-file encryption should not be required, merely strongly recommended.

Tox Client should have a **support** for encryption mandatory, and using encryption (IMHO) should be a default setting.

----

With that being said, should STS remain The Tox Client thing only, or perhaps be used also for stuff that isn't only about The Clients? And if that's the case, should there be a separate section of STS for Client compatibility, or perhaps a separate "document" whatsoever?

**Comment by GrayHatter** [comment]
One of the benefits of the STS is that it's one page. Perhaps something
like a footnote, one that lists the sections above that you should follow
if you plan to interact with STS clients without breaking them.

Bots that interact with clients should follow the STS but, there's
obviously no need for them to support profile encryption (maybe) but they
need to reject file transfers.

**Comment by Impyy** [comment]
I agree that support for encryption should be a requirement.
The reason I didn't add support for it to Toxy at the time was the fact that toxencryptsave functions crashed on me (this is still the case), but that's not very relevant to this discussion.
